### ISSUE TITLE
Email failed to send on 04/10/2017

### ISSUE THREAD

**Issue by XBigTK13X** [XBigTK13X/olava#7]
The website updated as usual. However, no email notifications were sent to the mailing list.

```
Loading configuration from /tmp/olava-config/environment.sh
Using the production mashape key
Reading in config for ENV: production
Hitting the GiantBomb API for 2017-04-10 00:00:00
Hitting the GiantBomb API for 2017-04-11 00:00:00
Hitting the GiantBomb API for 2017-04-12 00:00:00
Hitting the GiantBomb API for 2017-04-13 00:00:00
Hitting the GiantBomb API for 2017-04-14 00:00:00
Hitting the GiantBomb API for 2017-04-15 00:00:00
Hitting the GiantBomb API for 2017-04-16 00:00:00
Hitting GiantBomb API for https:--www.giantbomb.com-api-game-3030-49158-v11
Hitting GiantBomb API for https:--www.giantbomb.com-api-game-3030-57729-v11
Hitting GiantBomb API for https:--www.giantbomb.com-api-game-3030-50899-v11
Hitting GiantBomb API for https:--www.giantbomb.com-api-game-3030-43309-v11
Hitting GiantBomb API for https:--www.giantbomb.com-api-game-3030-52209-v11
Hitting GiantBomb API for https:--www.giantbomb.com-api-game-3030-43711-v11
Hitting GiantBomb API for https:--www.giantbomb.com-api-game-3030-45874-v11
Hitting GiantBomb API for https:--www.giantbomb.com-api-game-3030-57215-v11
Hitting GiantBomb API for https:--www.giantbomb.com-api-game-3030-54322-v11
There are 5 days this week with no releases
Found 9 unique game/release date combos within the next week
Index file written to /tmp/olava-output/index.html
Archive file written to /tmp/olava-output/archive/2017-04-10.html
Pickled raw data file written to /tmp/olava-output/archive/2017-04-10.pickle
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 135, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 66, in create_connection
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 782, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 215, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 144, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fe06e7efda0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 609, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 271, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='us10.api.mailchimp.com', port=443): Max retries exceeded with url: /3.0/campaigns (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fe06e7efda0>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 71, in <module>
    reporter.send(releaseCount)
  File "/root/olava/source/reporter.py", line 84, in send
    campaignId = createCampaign()
  File "/root/olava/source/reporter.py", line 24, in createCampaign
    json=params
  File "/usr/local/lib/python3.5/site-packages/requests/api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us10.api.mailchimp.com', port=443): Max retries exceeded with url: /3.0/campaigns (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fe06e7efda0>: Failed to establish a new connection: [Errno -2] Name or service not known',))```

**Comment by XBigTK13X** [comment]
This looks like a Digital Ocean networking hiccup. It shouldn't be a problem next week.
